/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class GutsValidator {
  constructor(schemaJson: string)
  parse(value: any): any
  parseStream(partialJson: string): boolean
}
